services:
  gforth:
    build: base/
    image: gforth/base
    container_name: gforth

  safe-gforth:
    build: safe/
    image: gforth/safe
    container_name: gforth-safe

  simple:
    build: simple/
    image: gforth/simple
    container_name: gforth-simple
    ports:
      - 8080:8080
